version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      RAILS_ENV: production
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: usamimi_production
      DB_HOST: db
    ports:
      - "5432:5432"

  usamimi:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0' -e 'production'"
    volumes:
      - .:/usamimi
    ports:
      - "3000:3000"
    depends_on:
      - db
