version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0
    steps:
      - checkout
      - run:
          name: Run RuboCop
          command: bundle exec rubocop
      - run:
          name: Run RSpec
          command: bundle exec rspec

  deploy:
    docker:
      - image: circleci/ruby:3.0
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            echo "machine https://api.heroku.com" >> ~/.netrc
            echo "  login $HEROKU_API_KEY" >> ~/.netrc
            echo "  password" >> ~/.netrc
            heroku git:remote --app 'usamimi'
            git push heroku master
